## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.154.180:3306/crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
## freemarker
freemarker:
  suffix: .ftlh
  content-type: text/html
  charset: UTF-8
  template-loader-path: classpath:/templates/

## 启用热部署
devtools:
  restart:
    enabled: true
    additional-paths: src/main/java
## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.lzx.crm.vo;com.lzx.crm.query;com.lzx.crm.dto
  configuration:
    map-underscore-to-camel-case: true
## pageHelper 分页
pagehelper:
  helper-dialect: mysql
## 设置 dao 日志打印级别
logging:
  level:
    com:
      lzx:
        crm:
          dao: debug